CREATE VIEW TVA AS
SELECT * FROM TVA1
UNION
SELECT * FROM TVA2;

CREATE VIEW PRODUIT AS
SELECT * FROM PRODUIT1
UNION
SELECT * FROM PRODUIT2;

CREATE VIEW ACHAT AS
SELECT ACHAT1.na, ACHAT1.nom, ACHAT1.np, ACHAT1.prix, ACHAT2.prenom, ACHAT2.nb
FROM ACHAT1
JOIN ACHAT2 ON ACHAT1.na = ACHAT2.na;

/* from herve's computer */
CREATE MATERIALIZED VIEW PERSONNE
REFRESH
complete start with (sysdate) next (sysdate+1/1440)
AS SELECT * FROM PERSONNE_MAJD_SYN;